//
//  VCLiterals.swift
//  RoyoConsultant
//
//  Created by Sandeep Kumar on 11/05/20.
//  Copyright © 2020 SandsHellCreations. All rights reserved.
//

import Foundation

enum VCLiteral: String {
    case FACEBOOK
    case GOOGLE
    case LOGIN_USING_EMAIL
    case LOGIN_USING_MOBILE
    case NEW_USER
    case TERMS_AGREED
    case SIGNUP
    case LOGIN_EMAIL_DESC
    case EMAIL_PLACEHOLDER
    case PSW_PLACEHOLDER
    case FORGOT_PASSWORD
    case NO_ACCOUNT
    case MOBILE_PACEHOLDER
    case LOGIN_USING_MOBILE_DESC
    case NAME_PLACEHOLDER
    case DOB_PLACEHOLDER
    case ReEnterPsw_PLACEHOLDER
    case BIO_PLACEHOLDER
    case ALREADY_REGISTER
    case LOGIN
    case BY_SIGNING_UP
    case TERMS
    case AND
    case PRIVACY
    case VERIFICATION
    case VERIFICATION_DESC
    case CODESENT
    case CODE_NOT_RECEIVED
    case RESEND_CODE
    case HOME
    case APPOINTMENTS
    case CHATS
    case VERSION
    case VERSION_INFO
    case HISTORY
    case NOTIFICATIONS
    case INVITE_PEOPLE
    case CONTACT_US
    case TERMS_AND_CONDITIONS
    case ABOUT
    case LOGOUT
    case CLASSES
    case WALLET
    case AGE
    case NA
    case MEET
    case WITH_EXPERTS
    case ALL
    case NEW
    case INPROGRESS
    case ACCEPT
    case COMPLETE
    case NO_ANSWER
    case BUSY
    case FAILED
    case SEARCH_FOR
    case AVAILABLE_PROFESSIONALS = "Available Healthcare professionals near you"
    case YR_EXP
    case YRS_EXP
    case CALL
    case CHAT
    case REVIEW
    case REVIEWS
    case PATIENTS
    case EXPERIECE
    case PHOTO
    case CHAT_THREAD_TIME
    case END_CHAT
    case END_CHAT_MESSAGE
    case CANCEL
    case CANCEL_APPOINTMENT
    case TRACK_STATUS
    case OK
    case AVAILABLE_BALANCE
    case ADD_MONEY
    case TRANSACTION_HISTORY
    case MONEY_SENT_TO
    case ADDED_TO_WALLET
    case INPUT_AMOUNT
    case AMOUNT
    case RETRY
    case DEBIT_CARD
    case CREDIT_CARD
    case GPAY
    case BHIM
    case PAY_AMOUNT
    case ADD_CARD
    case SCHEDULE
    case REQUEST_SENT_SUCCESS
    case WALLET_ALERT
    case WALLET_ALERT_MESSAGE
    case APP_TITLE_SUFFIX
    case APP_TITLE_PREFIX
    case PROFILE
    case LOGOUT_ALERT_MESSAGE
    case CANCELLED
    case RESCHEDULE
    case BOOKAGAIN
    case APPROVE
    case CANT_SEND_MESSAGE
    case FILTERS
    case APPLY
    case APPOINTMENT_DETAILS
    case RATE
    case RATING
    case SUBMIT
    case APPOINTMENT_REVIEW
    case REVIEW_PLACEHOLDER
    case CARD_ENDING_WITH
    case EDIT
    case DELETE
    case DELETE_CARD_MESSAGE
    case EDIT_CARD
    case UPDATE
    case CARD_EXP_PLACEHOLDER
    case CONFIRM_BOOKING
    case BOOKING_DETAILS
    case APPT_DATE_TIME
    case COUPON_PLACEHOLDER
    case PRICE_DETAILS
    case SUB_TOTAL
    case PROMO_APPLIED
    case TOTAL
    case TERMS_CONFIRM_BOOKING
    case PHONE_NUMBER
    case CHOOSE_DATE_TIME
    case NO_TIME_SLOTS
    case EDIT_SLOT
    case SLOT_FULL_ALERT
    case NO_CLASSES
    case OCCUPY_CLASS
    case OCCUPY_CLASS_ALERT_MESSAGE
    case JOIN_CLASS
    case YOU_NEED_ACCOUNT
    case SIGNUP_USING_MOBILE
    case BY_CONTINUE
    case ALREADY_ACCOUNT
    case USE_CODE
    case USERS_REMAINING
    case USER_REMAINING
    case COUPON_TITLE
    case CANCEL_REQUEST
    case CANCEL_REQUEST_ALERT
    case REFUND_FROM
    case NEW_MESSAGE
    case UPLOAD_ERROR
    case EDIT_PROFILE
    case REQUEST_NOW
    case INVALID_AMOUNT
    case NETWORK_ERROR
    case NO_APPOINTMENTS
    case NO_APPOINTMENTS_DESC
    case NO_CHAT
    case NO_CHAT_DESC
    case WALLET_NO_DATA
    case WALLET_NO_DATA_DESC
    case NO_HISTORY
    case NO_HISTORY_DESC
    case NOTIFICATION_NO_DATA
    case NOTIFICATION_NO_DATA_DESC
    case NO_CLASSES_FOR_CATEGORY
    case NO_CLASSES_FOR_CATEGORY_DESC
    case VENDOR_LISTING_NO_DATA
    case VENDOR_LISTING_NO_DATA_DESC
    case FORGOT_PSW_MESSAGE
    case PASSWORD_RESET_MESSAGE
    case APP_DESC
    case START_JOURNEY
    case ADDRESS
    case STATE
    case CITY
    case ZIP
    case DO_YOU_HAVE_INSURANCE
    case IF_YES_WHAT_INSURANCE
    case SELECT_INSURANCE
    case INSURANCE_TERMS_1
    case INSURANCE_TERMS_2
    case INSURANCE_TERMS_3
    case YES
    case NO
    case MINIMUM_INSURANCE_SELECT
    case TERMS_VALIDATION
    case UPDATE_TITLE
    case UPDATE_DESC
    case PACAKAGES
    case CHOOSE_PACKAGE
    case PAY
    case PAY_ALERT_MESSAGE
    case WALLET_ALERT_MESSAGE_PACKAGE
    case ADDED_PACKAGE
    case PACKAGE_NO_DATA
    case PACKAGE_NO_DATA_DESC
    case VIEW_ALL
    case BlOGS
    case ARTICLES
    case LATEST_BLOGS
    case LATEST_ARTICLES
    case SEARCH_SERVICE
    case REGISTER
    case REGISTER_DESC
    case FULL_NAME
    case REQESTING_SERVICE_FOR
    case IF_SERVICE_NOT_SELF
    case SELF
    case FATHER
    case MOTHER
    case CHILD
    case OTHER
    case HOME_CARE_REQUIREMENT
    case CHOOSE_HOME_CARE
    case SERVICE_ADDRESS
    case SERVICE_DATE
    case TERMS_INTELLGENT_MEMBER
    case CONTINUE
    case HOME_CARE_SELECTED
    case VERIFICATION_PENDING_TITLE
    case VERIFICATION_PENDING_DESC
    case ADD_ADDRESS
    case SELECT_DELIVERY_ADDRESS
    case CURRENT_LOCATION
    case LOCATION
    case CHANGE
    case ADDRESS_EXTRA_INFO
    case ADDRESS_EXTRA_INFO_ALERT
    case OTHER_SERVICE_FULL_NAME_ALERT
    case OTHER_SERVICE_MOBILE_ALERT
    case SELECT_ALL = "Select All"
    case HCR_ALERT
    case ADDRESS_ALERT
    case REGSITER_CAT_TERMS_ALERT
    case START_TIME
    case END_TIME
    case FROM
    case TO
    case ROS
    case BOOK_APPT
    case CALENDAR_DATE_ALERT
    case START_TIME_ALERT
    case END_TIME_ALERT
    case ROS_ALERT
    case HI_USER
    case GUEST_USER
    case REQUEST_UNDER_PROCESS
    case NO_NURSE_FOUND
    case ALLOCATED_NURSE
    case SIGN_UP_WITH_EMAIL
    case OR
    case LOGIN_WITH
    case SIGNUP_WITH
    case SIGNUP_ICARE
    case PersoanlInterest
    case WorkEnvironment
    case Covid
    case ProvidableServices
    case COMPLETING_PAYMENT
    case APPOINTMENT_CREATED
    case REACHED
    case STARTED
    case PICK_SERVICE_TEXT
    case PAYMENT_INFO
    case SAVE_ADDRESS_TYPE
    case SAVED_CARDS
    case NO_ADDRESS
    case NO_ADDRESS_DESC
    case WORK_ENVIRONMENT_ERROR
    case ESTIMATE_TIME
    case WorkEnvironmentCondition
    case BOOKING_HOURS_ERROR
    case PROVIDE_WORKING_HOURS
    case ADD_AVAILABILITY
    case MANAGE_AVAILABILITY

    var localized: String {
        return NSLocalizedString(self.rawValue, comment: "")
    }
}
